export type SeedService = {
  id: string;
  service_name: string;
  slug: string;
  category: string;
  short_description: string;
  product_brief: string;
  starting_price: string;
  estimated_timeline: string;
  status: string;
  featured: boolean;
  icon: string;
  best_for: string[];
  inclusions: string[];
  exclusions: string[];
  stack: { category: string; technology: string }[];
  requirements: string[];
  deliverables: string[];
  addons: { addon_name: string; description: string; price: string }[];
  faqs: { question: string; answer: string }[];
  notes: string;
};

export const DEFAULT_SERVICES: SeedService[] = [
  {
    id: "svc-business-website",
    service_name: "Business Website",
    slug: "business-website",
    category: "Website Design",
    short_description: "A professional, mobile-friendly website built to represent your business online — fast, SEO-ready, and designed to convert visitors into customers.",
    product_brief: "Every business needs a professional online presence. A Business Website from Cyberussell is more than just a pretty page — it's a 24/7 sales tool that works while you sleep. We combine modern web design with AI-assisted content writing and SEO fundamentals to build a site that looks great, loads fast, and ranks on Google. Whether you're a restaurant, clinic, freelancer, or small business owner, this service gives you a credible digital home base. We handle everything from design and copywriting to deployment — so you don't need any technical knowledge.",
    starting_price: "₱7,999",
    estimated_timeline: "5–7 business days",
    status: "active",
    featured: true,
    icon: "🌐",
    best_for: ["Small Businesses", "Restaurants", "Clinics", "Professionals", "Freelancers", "Real Estate", "Schools"],
    inclusions: [
      "Discovery & planning session",
      "Up to 5 pages (Home, About, Services, Contact, + 1 custom page)",
      "Mobile-responsive design",
      "AI-assisted copywriting for all pages",
      "Basic on-page SEO (meta tags, headings, sitemap)",
      "Contact form setup",
      "Google Maps integration",
      "Social media links",
      "Deployment to custom domain",
      "1 round of revisions after delivery",
    ],
    exclusions: [
      "Domain registration & annual renewal",
      "Hosting fees (after free tier)",
      "E-commerce / online store functionality",
      "Ongoing monthly maintenance",
      "Logo design (available as add-on)",
      "Stock photography (client must provide or purchase)",
      "Unlimited revisions",
      "Paid advertising setup",
    ],
    stack: [
      { category: "Frontend", technology: "Next.js" },
      { category: "Frontend", technology: "React" },
      { category: "Frontend", technology: "Tailwind" },
      { category: "Frontend", technology: "TypeScript" },
      { category: "Hosting", technology: "Vercel" },
      { category: "AI", technology: "Claude" },
    ],
    requirements: [
      "Business name and tagline",
      "Logo file (PNG or SVG)",
      "Brand colors (hex codes or references)",
      "Business photos (minimum 5)",
      "List of services with descriptions",
      "Contact information (address, phone, email)",
      "Preferred domain name",
      "Google account (for Google Maps & Analytics)",
    ],
    deliverables: [
      "Live website on your domain",
      "Source code (GitHub repository)",
      "Admin access credentials",
      "Basic SEO report",
      "Training video (how to update content)",
    ],
    addons: [
      { addon_name: "Logo Design", description: "Professional logo in PNG, SVG, and PDF formats", price: "₱2,499" },
      { addon_name: "Extra Pages", description: "Each additional page beyond the 5-page limit", price: "₱999/page" },
      { addon_name: "Blog Setup", description: "Fully functional blog with CMS", price: "₱1,999" },
      { addon_name: "Monthly Maintenance", description: "Updates, backups, and performance monitoring", price: "₱999/month" },
      { addon_name: "SEO Package", description: "Full keyword research, on-page SEO, and Google Search Console setup", price: "₱2,999" },
    ],
    faqs: [
      { question: "Do I need to know how to code?", answer: "Not at all. We handle everything technical. You just provide your content and feedback, and we deliver a ready-to-use website." },
      { question: "How long does it take?", answer: "Typically 5–7 business days after we receive all required materials from you. Delays in providing content will extend the timeline." },
      { question: "Can I update the website myself after launch?", answer: "Yes. We build with easy-to-update systems and provide a training video so you can make basic changes without help." },
      { question: "What if I already have a website?", answer: "We can redesign your existing site or migrate it to a better platform. Contact us to discuss your current setup." },
      { question: "Is hosting included?", answer: "Deployment is included. Vercel's free tier covers most small business websites. If your traffic grows beyond the free tier, hosting costs may apply." },
    ],
    notes: "Upsell opportunity: offer SEO package and blog setup together. Most restaurants and clinics need the Google Maps + booking integration. Consider offering a package bundle.",
  },
  {
    id: "svc-business-automation",
    service_name: "Business Automation",
    slug: "business-automation",
    category: "AI Automation",
    short_description: "Automate repetitive business tasks using AI and no-code tools — save hours every week without hiring extra staff.",
    product_brief: "Repetitive tasks are the biggest time drain in any business. Business Automation by Cyberussell identifies the workflows eating your time — whether it's manual data entry, sending follow-up messages, generating reports, or processing inquiries — and replaces them with automated systems. We use a combination of n8n, Google Apps Script, and AI models to build workflows tailored to your exact operations. No technical knowledge required. You describe the problem, we build the solution. Most clients recover their investment in the first month.",
    starting_price: "₱4,999",
    estimated_timeline: "3–5 business days",
    status: "active",
    featured: true,
    icon: "⚙️",
    best_for: ["Small Businesses", "Freelancers", "Clinics", "Restaurants", "E-commerce", "Startups", "Real Estate"],
    inclusions: [
      "Business process audit (identify automation opportunities)",
      "Up to 3 automation workflows",
      "Integration with existing tools (Gmail, Google Sheets, WhatsApp, Facebook, etc.)",
      "AI-powered data processing where applicable",
      "Testing and quality assurance",
      "Documentation of all workflows",
      "1-hour walkthrough and training session",
      "30-day post-launch support",
    ],
    exclusions: [
      "More than 3 workflows (available as add-on)",
      "Custom app or software development",
      "Paid API costs (third-party tools)",
      "Ongoing workflow management",
      "Hardware or physical system integration",
    ],
    stack: [
      { category: "Automation", technology: "n8n" },
      { category: "Automation", technology: "Google Apps Script" },
      { category: "Automation", technology: "Make" },
      { category: "AI", technology: "OpenAI API" },
      { category: "AI", technology: "Claude" },
      { category: "Analytics", technology: "Google Analytics" },
    ],
    requirements: [
      "Description of current manual processes (written or voice note)",
      "Access to tools you want connected (Google, Facebook, etc.)",
      "List of repetitive tasks you want eliminated",
      "Sample data (if applicable)",
      "Google account for Google Sheets/Apps Script",
    ],
    deliverables: [
      "Up to 3 live automation workflows",
      "Workflow documentation (PDF)",
      "Training recording",
      "Source files / n8n JSON exports",
      "30-day support access",
    ],
    addons: [
      { addon_name: "Additional Workflows", description: "Each workflow beyond the 3 included", price: "₱1,500/workflow" },
      { addon_name: "Monthly Monitoring", description: "Monthly check-in, error fixes, and workflow optimization", price: "₱1,999/month" },
      { addon_name: "AI Chatbot Integration", description: "Add an AI-powered chatbot to your workflow", price: "₱3,999" },
      { addon_name: "WhatsApp Automation", description: "Automated WhatsApp responses and follow-ups", price: "₱2,499" },
    ],
    faqs: [
      { question: "What kinds of tasks can be automated?", answer: "Common examples include: sending follow-up messages to leads, generating weekly reports from Google Sheets, auto-posting to social media, processing inquiry forms, sending receipts, and scheduling reminders." },
      { question: "Do I need to be technical to use the automations?", answer: "No. We build the systems and train you to use them. Most automations run in the background with zero effort from you once set up." },
      { question: "What tools do you integrate with?", answer: "Gmail, Google Sheets, Google Forms, Facebook Pages, WhatsApp (via API), Notion, Airtable, Slack, and most apps with an API or webhook support." },
      { question: "What if the automation breaks?", answer: "We provide 30 days of free support after delivery. After that, our monthly monitoring plan covers ongoing maintenance." },
    ],
    notes: "Great upsell: offer the monthly monitoring add-on proactively. Most clients don't realize they'll need it until something breaks. Bundle with AI Systems for larger clients.",
  },
  {
    id: "svc-ai-systems",
    service_name: "AI Systems",
    slug: "ai-systems",
    category: "AI Automation",
    short_description: "Custom AI-powered systems built for your business — chatbots, AI assistants, document processors, and intelligent workflows.",
    product_brief: "This is not a generic chatbot. AI Systems by Cyberussell are purpose-built AI solutions trained on your business context — your products, your tone, your policies. We build AI assistants that answer customer questions, process documents, generate reports, qualify leads, and handle tasks that used to require a human. Whether you need a customer service bot for your Facebook page, an AI that reads and summarizes PDFs, or an internal assistant that knows your entire service catalog — we build it, deploy it, and make it work exactly the way your business needs it to.",
    starting_price: "₱3,999",
    estimated_timeline: "5–10 business days",
    status: "active",
    featured: false,
    icon: "🤖",
    best_for: ["Small Businesses", "E-commerce", "Clinics", "Real Estate", "Startups", "Freelancers"],
    inclusions: [
      "AI system design and architecture",
      "Custom prompt engineering and system instructions",
      "Integration with one platform (Facebook, website, WhatsApp, or internal)",
      "Knowledge base setup (your business info, FAQs, products)",
      "Testing with real-world scenarios",
      "Deployment and configuration",
      "Training on how to update and manage the AI",
      "30-day post-launch support",
    ],
    exclusions: [
      "Multiple platform integrations (add-on)",
      "Custom AI model training (large-scale ML projects)",
      "Paid AI API costs after deployment",
      "Ongoing prompt updates and knowledge base maintenance",
      "Physical hardware integration",
    ],
    stack: [
      { category: "AI", technology: "Claude" },
      { category: "AI", technology: "OpenAI API" },
      { category: "AI", technology: "Anthropic API" },
      { category: "Automation", technology: "n8n" },
      { category: "Backend", technology: "Supabase" },
    ],
    requirements: [
      "Description of what the AI should do",
      "Your business information (services, pricing, policies, FAQs)",
      "Access to the platform where AI will be deployed",
      "Sample conversations or common customer questions",
      "Preferred tone and personality for the AI",
    ],
    deliverables: [
      "Live AI system on your chosen platform",
      "System prompt documentation",
      "Knowledge base file",
      "Admin guide (how to update the AI)",
      "30-day support access",
    ],
    addons: [
      { addon_name: "Additional Platform", description: "Deploy the same AI to a second platform (e.g. website + WhatsApp)", price: "₱1,999" },
      { addon_name: "Monthly Maintenance", description: "Knowledge base updates, prompt tuning, and performance review", price: "₱1,499/month" },
      { addon_name: "Lead Qualification Module", description: "AI that qualifies and scores leads before forwarding to you", price: "₱2,999" },
      { addon_name: "Document Processing", description: "AI that reads, extracts, and summarizes uploaded documents", price: "₱3,499" },
    ],
    faqs: [
      { question: "What is the difference between a chatbot and an AI system?", answer: "A chatbot follows fixed scripts. An AI system understands natural language, handles unexpected questions, remembers context within a conversation, and gives human-like answers based on your specific business knowledge." },
      { question: "Will the AI know about my specific products and services?", answer: "Yes. We build a knowledge base from your business information and train the AI to answer questions about your specific offerings, pricing, and policies." },
      { question: "What happens when the AI doesn't know the answer?", answer: "We program fallback responses that gracefully escalate to a human or collect the customer's contact info for follow-up." },
      { question: "Are there ongoing costs?", answer: "AI API usage (OpenAI or Anthropic) is billed directly to you. Most small businesses spend ₱500–₱2,000/month on API costs depending on volume." },
    ],
    notes: "This is the highest-growth service. Position it as ROI-positive: replaces a human customer service rep costing ₱15,000/month. Emphasize the 24/7 availability angle.",
  },
  {
    id: "svc-custom-software",
    service_name: "Custom Business Software",
    slug: "custom-business-software",
    category: "Web App",
    short_description: "Tailor-made web applications built to solve your exact business problem — inventory systems, booking platforms, CRM tools, and more.",
    product_brief: "Off-the-shelf software rarely fits your business perfectly. Custom Business Software from Cyberussell means you get exactly what you need — nothing more, nothing less. We build web-based applications that handle your specific workflows: an inventory tracking system for your warehouse, a booking platform for your clinic, a customer database for your sales team, or a custom dashboard for your operations. Built with modern tech (Next.js, Supabase), these apps are fast, secure, and scalable. Because we use AI-assisted development, we can deliver at a fraction of the cost and time of traditional agencies.",
    starting_price: "Starting at ₱24,999",
    estimated_timeline: "3–6 weeks",
    status: "active",
    featured: false,
    icon: "💻",
    best_for: ["Small Businesses", "Clinics", "Restaurants", "Startups", "Schools", "Real Estate", "E-commerce"],
    inclusions: [
      "Requirements gathering and system design",
      "Database architecture and setup",
      "Full-stack web application development",
      "User authentication and role management",
      "Admin dashboard",
      "Mobile-responsive interface",
      "Testing and bug fixes",
      "Deployment to production",
      "2 weeks post-launch support",
      "Technical documentation",
    ],
    exclusions: [
      "Mobile app (iOS/Android native)",
      "Third-party API subscription costs",
      "Ongoing hosting fees",
      "Feature additions after project scope is defined",
      "Data migration from existing legacy systems (available as add-on)",
      "Staff training beyond 1 session",
    ],
    stack: [
      { category: "Frontend", technology: "Next.js" },
      { category: "Frontend", technology: "React" },
      { category: "Frontend", technology: "TypeScript" },
      { category: "Frontend", technology: "Tailwind" },
      { category: "Backend", technology: "Supabase" },
      { category: "Backend", technology: "PostgreSQL" },
      { category: "Hosting", technology: "Vercel" },
      { category: "AI", technology: "GitHub Copilot" },
    ],
    requirements: [
      "Detailed description of the software's purpose",
      "List of features and user flows (can be rough)",
      "User roles (who will use it: admin, staff, customers)",
      "Any existing data that needs to be imported",
      "Preferred domain or subdomain",
      "Design preferences or references",
    ],
    deliverables: [
      "Live web application on your domain",
      "Source code (GitHub repository)",
      "Database schema documentation",
      "Admin access and credentials",
      "User manual (PDF)",
      "Training session (1 hour)",
    ],
    addons: [
      { addon_name: "Data Migration", description: "Import and clean data from existing systems (Excel, old software, etc.)", price: "₱4,999+" },
      { addon_name: "Monthly Support", description: "Bug fixes, minor feature updates, and performance monitoring", price: "₱2,999/month" },
      { addon_name: "Additional Features", description: "Scoped and priced per feature after project delivery", price: "Quoted separately" },
      { addon_name: "Staff Training Package", description: "Additional training sessions for your team", price: "₱1,999/session" },
    ],
    faqs: [
      { question: "How is this different from buying off-the-shelf software?", answer: "Generic software like QuickBooks or Shopify has features you don't need and lacks features specific to your business. Custom software is built exactly for your workflow, reducing friction and training time." },
      { question: "Can I add features later?", answer: "Yes. We build with scalability in mind. Additional features can be scoped and priced after the initial project." },
      { question: "Is my data secure?", answer: "Yes. We use Supabase (backed by PostgreSQL) with row-level security, encrypted connections, and proper authentication — the same infrastructure used by major tech companies." },
      { question: "What if the scope changes mid-project?", answer: "We do a detailed requirements session before starting. Scope changes after work begins are handled as separate add-ons to protect both parties." },
    ],
    notes: "Highest-value service. Requires the most detailed discovery call. Always get requirements in writing before starting. Typical clients: clinics needing patient management, small distributors needing inventory tracking, schools needing enrollment systems.",
  },
  {
    id: "svc-bubble-development",
    service_name: "Bubble.io Development",
    slug: "bubble-development",
    category: "Web App",
    short_description: "Fast, powerful web apps built with Bubble.io — the no-code platform that lets us ship complex software in days, not months.",
    product_brief: "Bubble.io is the world's most powerful no-code platform — and in the right hands, it can build software that rivals developer-built apps at a fraction of the cost and time. At Cyberussell, we are Bubble specialists who can build marketplaces, SaaS products, booking systems, CRMs, and member portals — all without writing a single line of traditional code. Bubble apps live in the cloud, are automatically hosted, and can scale with your business. If you need a working product fast, Bubble.io is often the smartest path forward.",
    starting_price: "Starting at ₱8,999",
    estimated_timeline: "1–3 weeks",
    status: "active",
    featured: false,
    icon: "🫧",
    best_for: ["Startups", "Small Businesses", "Freelancers", "E-commerce", "Professionals"],
    inclusions: [
      "App design and wireframing",
      "Full Bubble.io build",
      "Database design within Bubble",
      "User authentication",
      "Responsive design for desktop and mobile",
      "Plugin configuration",
      "Testing across browsers and devices",
      "Deployment to your Bubble subdomain or custom domain",
      "Video walkthrough of the app",
    ],
    exclusions: [
      "Bubble.io subscription cost (paid by client)",
      "Third-party plugin costs",
      "Native mobile app (iOS/Android)",
      "Ongoing Bubble maintenance",
      "Data migration from other platforms",
    ],
    stack: [
      { category: "Frontend", technology: "Bubble.io" },
      { category: "AI", technology: "OpenAI API" },
      { category: "Automation", technology: "Zapier" },
      { category: "Analytics", technology: "Google Analytics" },
    ],
    requirements: [
      "Description of what the app should do",
      "User flows and key features",
      "Design references or mood board",
      "Bubble.io account (we can help you create one)",
      "List of third-party services to integrate",
    ],
    deliverables: [
      "Live Bubble.io application",
      "Full ownership transferred to your Bubble account",
      "Walkthrough video",
      "Feature documentation",
    ],
    addons: [
      { addon_name: "AI Features", description: "Integrate OpenAI or Claude into your Bubble app for intelligent features", price: "₱2,999" },
      { addon_name: "Custom Domain Setup", description: "Connect your own domain to the Bubble app", price: "₱999" },
      { addon_name: "Monthly Maintenance", description: "Bug fixes, plugin updates, and minor feature tweaks", price: "₱1,999/month" },
      { addon_name: "Stripe / PayMongo Payments", description: "Full payment processing integration", price: "₱2,499" },
    ],
    faqs: [
      { question: "Do I need my own Bubble account?", answer: "Yes. You'll need a Bubble.io subscription (starts at $32/month). We work inside your account so you own everything." },
      { question: "Is Bubble suitable for serious businesses?", answer: "Absolutely. Companies like Qoins, Dividend Finance, and Teal have raised millions using Bubble-built products. It's production-grade software." },
      { question: "Can Bubble apps handle lots of users?", answer: "Yes. Bubble's infrastructure scales. For high-traffic apps, upgrading your Bubble plan adds more capacity automatically." },
      { question: "What can't Bubble do?", answer: "Bubble struggles with very complex real-time features (like multiplayer games), native mobile apps, and extreme data-processing tasks. For those cases, custom development is better." },
    ],
    notes: "Bubble is fastest for MVP-type projects. Great for clients who want to validate a business idea quickly before investing in custom code. Mention the speed advantage vs traditional dev.",
  },
  {
    id: "svc-seo-optimization",
    service_name: "SEO Optimization",
    slug: "seo-optimization",
    category: "SEO",
    short_description: "Get your business found on Google — keyword research, on-page SEO, technical fixes, and content strategy backed by AI.",
    product_brief: "95% of clicks go to the first page of Google. If you're not there, your competitors are getting your customers. SEO Optimization by Cyberussell uses a combination of AI-powered keyword research, on-page optimization, and technical SEO fixes to move your website up in the rankings. We don't do black-hat tricks or shortcuts — we build real, sustainable search visibility that grows over time. Every action we take is documented so you know exactly what was done and why. Most clients see measurable ranking improvements within 30–60 days.",
    starting_price: "₱2,999",
    estimated_timeline: "5–7 business days",
    status: "active",
    featured: false,
    icon: "🔍",
    best_for: ["Small Businesses", "Restaurants", "Clinics", "Real Estate", "E-commerce", "Freelancers", "Professionals"],
    inclusions: [
      "Full website SEO audit",
      "Keyword research (up to 20 target keywords)",
      "Competitor analysis (top 3 competitors)",
      "On-page SEO optimization (meta titles, descriptions, headings, image alt text)",
      "Internal linking improvements",
      "Google Search Console setup and submission",
      "XML sitemap creation and submission",
      "Page speed basic fixes",
      "SEO strategy report with 90-day action plan",
    ],
    exclusions: [
      "Monthly ongoing SEO management",
      "Content creation (blog articles, landing pages)",
      "Link building / backlink outreach",
      "Google Ads / paid search",
      "Social media management",
      "Website redesign",
    ],
    stack: [
      { category: "Analytics", technology: "Google Analytics" },
      { category: "Analytics", technology: "Search Console" },
      { category: "AI", technology: "Claude" },
      { category: "AI", technology: "ChatGPT" },
    ],
    requirements: [
      "Website URL and access (admin login or FTP)",
      "Google account (for Search Console and Analytics)",
      "Target location (city/region to rank in)",
      "List of main services or products",
      "Main competitors (if known)",
    ],
    deliverables: [
      "Full SEO audit report (PDF)",
      "Keyword research spreadsheet",
      "On-page SEO changes (applied directly to site)",
      "Competitor analysis summary",
      "90-day SEO action plan",
      "Google Search Console access configured",
    ],
    addons: [
      { addon_name: "Monthly SEO Management", description: "Ongoing SEO monitoring, keyword tracking, and monthly report", price: "₱1,999/month" },
      { addon_name: "Blog Content Package", description: "4 SEO-optimized blog articles per month (AI-assisted + edited)", price: "₱2,999/month" },
      { addon_name: "Local SEO", description: "Google Business Profile optimization for local search visibility", price: "₱1,499" },
      { addon_name: "Link Building", description: "Manual outreach to earn quality backlinks from relevant sites", price: "₱2,499/month" },
    ],
    faqs: [
      { question: "How long until I see results?", answer: "SEO is a long-term investment. Most clients see initial ranking improvements within 30–60 days. Significant traffic increases typically happen at the 3–6 month mark with consistent effort." },
      { question: "Do you guarantee first-page rankings?", answer: "No ethical SEO agency can guarantee rankings — Google's algorithm changes constantly. We guarantee real, documented work using best practices that consistently improve ranking positions over time." },
      { question: "Will this work for a new website?", answer: "Yes, but new sites take longer to rank. We establish the right foundation so the site builds authority over time." },
      { question: "What is the difference between SEO and Google Ads?", answer: "Google Ads gives you immediate but paid traffic. SEO builds organic (free) traffic that compounds over time. Most businesses benefit from both, but SEO has a much better long-term ROI." },
    ],
    notes: "Best paired with the website service or blog content package. Local businesses (clinics, restaurants) benefit most from Local SEO add-on. Monthly retainer is the real revenue play here.",
  },
  {
    id: "svc-ai-content-creation",
    service_name: "AI Content Creation",
    slug: "ai-content-creation",
    category: "Content",
    short_description: "A month of professional content for your business — social media posts, captions, blog articles, and email newsletters — powered by AI and edited by humans.",
    product_brief: "Content is king, but creating it consistently is exhausting. AI Content Creation by Cyberussell takes the entire content process off your plate. We use AI to research, draft, and structure your content — then human editors refine it to match your brand voice. You get a full month of ready-to-post content: social media captions, blog articles, and email newsletters — without spending hours staring at a blank screen. The result is consistent, professional content that builds your audience and positions you as an expert in your field.",
    starting_price: "₱1,999",
    estimated_timeline: "3–5 business days",
    status: "active",
    featured: false,
    icon: "✍️",
    best_for: ["Small Businesses", "Freelancers", "Content Creators", "Professionals", "E-commerce", "Clinics"],
    inclusions: [
      "Brand voice discovery questionnaire",
      "Content strategy and topic planning",
      "20 social media posts (Facebook/Instagram captions)",
      "4 blog article outlines (800–1,200 words each)",
      "2 email newsletter drafts",
      "Hashtag sets for each post",
      "Content calendar (Google Sheet)",
      "1 round of revisions",
    ],
    exclusions: [
      "Graphic design / visual creation (available as add-on)",
      "Video scripting",
      "Content scheduling and posting",
      "Ongoing monthly management",
      "Paid advertising copy",
      "Translation to other languages",
    ],
    stack: [
      { category: "AI", technology: "Claude" },
      { category: "AI", technology: "ChatGPT" },
      { category: "AI", technology: "Gemini" },
    ],
    requirements: [
      "Business name, industry, and target audience",
      "Brand voice description (or examples of content you like)",
      "List of topics or themes to cover",
      "Any upcoming promotions or events",
      "Google account (for shared Google Sheet)",
    ],
    deliverables: [
      "20 ready-to-post social media captions",
      "4 blog articles (full draft)",
      "2 email newsletter drafts",
      "Hashtag sets",
      "Content calendar (30 days)",
    ],
    addons: [
      { addon_name: "Social Media Graphics", description: "20 designed graphics matching your brand (Canva-based)", price: "₱1,499" },
      { addon_name: "Video Scripts", description: "4 short-form video scripts (TikTok/Reels format)", price: "₱999" },
      { addon_name: "Monthly Content Package", description: "Recurring monthly content: posts, blogs, and newsletters", price: "₱1,999/month" },
      { addon_name: "Content Scheduling", description: "Schedule and publish all content for you for the month", price: "₱999/month" },
    ],
    faqs: [
      { question: "Will the content sound like it was written by AI?", answer: "No. We use AI to draft and structure, then human editors refine the content to match your brand voice. The final output reads naturally and professionally." },
      { question: "Can I request specific topics?", answer: "Yes. We work from your topic list. If you don't have one, we suggest topics based on your industry and audience." },
      { question: "Do you handle posting on social media?", answer: "Content creation and scheduling are separate services. We deliver ready-to-post content; the scheduling add-on covers publishing." },
      { question: "What platforms is this content for?", answer: "The social media captions are optimized for Facebook and Instagram. We can adapt for LinkedIn, TikTok, or Twitter/X at your request." },
    ],
    notes: "Recurring service with high retention. Most clients upgrade to the monthly package after the first batch. Lead with the time savings angle — 'stop spending 10 hours a week on content'.",
  },
  {
    id: "svc-business-documentation",
    service_name: "Business Documentation",
    slug: "business-documentation",
    category: "Content",
    short_description: "Professional business documents created with AI — SOPs, employee handbooks, service agreements, business plans, and more.",
    product_brief: "Most small businesses run on informal systems — knowledge stuck in the owner's head, verbal agreements, and inconsistent processes. Business Documentation by Cyberussell formalizes your operations. We use AI to generate professional Standard Operating Procedures (SOPs), employee handbooks, service agreements, client contracts, and business plans — customized to your specific business. These documents protect your business legally, help you onboard staff faster, and make your operations scalable. Whether you're preparing to hire your first employee or seeking investment, professional documentation signals that you're a serious operation.",
    starting_price: "₱2,999",
    estimated_timeline: "3–5 business days",
    status: "active",
    featured: false,
    icon: "📄",
    best_for: ["Small Businesses", "Freelancers", "Startups", "Clinics", "Schools", "Professionals"],
    inclusions: [
      "Needs assessment call (30 min)",
      "Up to 3 core business documents",
      "AI-assisted drafting with human refinement",
      "Professional formatting and layout",
      "Delivered in Word (.docx) and PDF formats",
      "1 round of revisions",
    ],
    exclusions: [
      "More than 3 documents (available as add-on)",
      "Legal review or notarization (consult a licensed attorney)",
      "Translation to other languages",
      "Ongoing document management",
      "Government permit applications",
    ],
    stack: [
      { category: "AI", technology: "Claude" },
      { category: "AI", technology: "ChatGPT" },
    ],
    requirements: [
      "Business name, type, and registered address",
      "Description of your services or products",
      "Team size and structure",
      "Types of documents needed",
      "Any existing documents for reference",
    ],
    deliverables: [
      "Up to 3 professional business documents",
      "Word (.docx) format (editable)",
      "PDF format (print-ready)",
    ],
    addons: [
      { addon_name: "Additional Document", description: "Each document beyond the 3 included", price: "₱999/document" },
      { addon_name: "Full SOP Package", description: "Complete set of SOPs for a specific department (5–8 documents)", price: "₱5,999" },
      { addon_name: "Business Plan", description: "Comprehensive business plan with financials, market analysis, and strategy", price: "₱4,999" },
    ],
    faqs: [
      { question: "Are the contracts legally binding?", answer: "Our documents follow standard professional formats. However, for legally sensitive agreements, we strongly recommend having a licensed attorney review before use." },
      { question: "What types of documents can you create?", answer: "SOPs, employee handbooks, service agreements, client contracts, NDAs, proposals, business plans, policies, onboarding guides, and more." },
      { question: "Can I edit the documents myself after delivery?", answer: "Yes. We deliver in .docx format so you can update them as your business grows." },
    ],
    notes: "Great add-on for new business website clients. Pair documentation with automation — if they have SOPs, we can automate parts of them.",
  },
  {
    id: "svc-business-research",
    service_name: "Business Research",
    slug: "business-research",
    category: "Consultation",
    short_description: "AI-powered market research, competitor analysis, and business intelligence — delivered as a clear, actionable report.",
    product_brief: "Making business decisions without data is guesswork. Business Research by Cyberussell uses AI tools to conduct deep market research in hours — not weeks. We research your target market, analyze your competitors, identify gaps and opportunities, and deliver it all as a clean, actionable report you can actually use. Whether you're validating a new business idea, exploring a new market, benchmarking against competitors, or preparing a pitch for investors — our research gives you the intelligence you need to make confident decisions.",
    starting_price: "₱1,999",
    estimated_timeline: "2–3 business days",
    status: "active",
    featured: false,
    icon: "🔬",
    best_for: ["Startups", "Small Businesses", "Freelancers", "Professionals", "E-commerce"],
    inclusions: [
      "Research brief discussion (30 min call or written brief)",
      "Market overview and size estimate",
      "Top 5 competitor analysis",
      "Target audience profile",
      "Key trends and opportunities",
      "SWOT analysis",
      "Actionable recommendations",
      "Full research report (PDF, 10–20 pages)",
    ],
    exclusions: [
      "Primary research (surveys, interviews, focus groups)",
      "Financial modeling or projections",
      "Legal or regulatory compliance advice",
      "Ongoing market monitoring",
      "Industry-specific data subscriptions",
    ],
    stack: [
      { category: "AI", technology: "Claude" },
      { category: "AI", technology: "ChatGPT" },
      { category: "AI", technology: "Gemini" },
    ],
    requirements: [
      "Research topic or business idea",
      "Target market / location",
      "Main competitors (if known)",
      "Specific questions you want answered",
      "Purpose of the research (investment pitch, product launch, etc.)",
    ],
    deliverables: [
      "Market research report (PDF, 10–20 pages)",
      "Competitor analysis spreadsheet",
      "Target audience profile",
      "Key recommendations summary (1 page)",
    ],
    addons: [
      { addon_name: "Financial Projections", description: "3-year revenue and expense projections in Excel", price: "₱2,999" },
      { addon_name: "Investor Pitch Deck", description: "Professional 10-slide pitch deck based on research findings", price: "₱3,999" },
      { addon_name: "Monthly Market Updates", description: "Monthly brief on market changes, competitor moves, and new opportunities", price: "₱1,499/month" },
    ],
    faqs: [
      { question: "How accurate is AI-powered research?", answer: "AI research is highly effective for publicly available information — market trends, competitor positioning, consumer behavior patterns. We verify key data points and clearly note when information is estimated vs confirmed." },
      { question: "Can I use this for an investor pitch?", answer: "Yes. Many of our clients use the research report as the foundation for their pitch deck. We can also build the deck as an add-on." },
      { question: "What if I need research on a very niche industry?", answer: "We can research any industry. Niche industries may have less publicly available data, but AI tools are still effective at synthesizing what exists." },
    ],
    notes: "Often the entry point for new clients. If they validate their idea, they come back for website + automation. Position as a low-risk first engagement.",
  },
  {
    id: "svc-website-maintenance",
    service_name: "Website Maintenance",
    slug: "website-maintenance",
    category: "Website Design",
    short_description: "Monthly website care — updates, backups, performance monitoring, and security checks — so your site stays fast and secure year-round.",
    product_brief: "A website is not a one-time project — it's a living asset that needs regular care. Website Maintenance by Cyberussell gives you peace of mind with monthly updates, automated backups, uptime monitoring, and security checks. We handle the technical side so you can focus on running your business. Whether your content needs updating, a plugin is causing issues, or you just want someone to watch over your site — we're your dedicated website team. Most business owners don't realize how fragile an unmaintained website becomes over time. We prevent problems before they become emergencies.",
    starting_price: "₱999/month",
    estimated_timeline: "Ongoing monthly service",
    status: "active",
    featured: false,
    icon: "🛠️",
    best_for: ["Small Businesses", "Restaurants", "Clinics", "Professionals", "Schools", "Real Estate"],
    inclusions: [
      "Monthly content updates (up to 3 changes)",
      "Plugin and dependency updates",
      "Automated daily backups",
      "Uptime monitoring (24/7)",
      "Monthly performance report",
      "Security scan",
      "Broken link check",
      "Priority support response (within 24 hours)",
    ],
    exclusions: [
      "Major redesign or new pages",
      "New feature development",
      "SEO management",
      "Content creation (blog articles, social media)",
      "E-commerce order management",
    ],
    stack: [
      { category: "Frontend", technology: "Next.js" },
      { category: "Hosting", technology: "Vercel" },
      { category: "Analytics", technology: "Google Analytics" },
      { category: "Analytics", technology: "Search Console" },
    ],
    requirements: [
      "Website URL and admin access",
      "Hosting platform access",
      "Domain registrar access (for SSL monitoring)",
      "Google account (for Analytics/Search Console)",
    ],
    deliverables: [
      "Monthly maintenance report",
      "Backup confirmation",
      "Performance metrics summary",
      "List of changes made each month",
    ],
    addons: [
      { addon_name: "Emergency Support", description: "Same-day response for critical issues (site down, hacked, etc.)", price: "₱1,499/incident" },
      { addon_name: "Content Updates (Extra)", description: "Additional content changes beyond the 3 included", price: "₱299/change" },
      { addon_name: "SEO Monthly Add-on", description: "Add monthly SEO monitoring and reporting", price: "₱1,499/month" },
      { addon_name: "New Page", description: "Add a new page to the existing website", price: "₱999/page" },
    ],
    faqs: [
      { question: "What counts as a 'content update'?", answer: "Changing text, swapping an image, updating a price, adding a phone number, changing business hours — any edit that doesn't require building a new section or page." },
      { question: "What happens if my site goes down?", answer: "Our uptime monitoring alerts us immediately. We investigate and fix the issue within our agreed response time (24 hours for standard, same-day for Emergency Support add-on)." },
      { question: "Can I cancel anytime?", answer: "Yes. This is a month-to-month service. Cancel anytime with 30 days notice." },
      { question: "Do you maintain websites you didn't build?", answer: "Yes, if the site is built with technologies we support (Next.js, WordPress, Webflow, Wix). We'll do an initial audit first to assess the site's condition." },
    ],
    notes: "Highest recurring revenue product. Every website client should be offered this immediately after launch. Create a bundle: Website + 3 months maintenance at a discount to get them on the retainer.",
  },
  {
    id: "svc-ai-training",
    service_name: "AI Training",
    slug: "ai-training",
    category: "Consultation",
    short_description: "Hands-on AI training for business owners and teams — learn to use ChatGPT, Claude, and AI tools to save time and grow your business.",
    product_brief: "Most business owners know AI is important — but they don't know where to start. AI Training by Cyberussell bridges that gap with practical, hands-on sessions designed for real business applications. We don't teach theory. We teach you how to use ChatGPT, Claude, and other AI tools to do your actual daily work faster and better — write emails, create content, build presentations, research competitors, answer customer questions, and automate tasks. Training is tailored to your industry, your role, and your specific business challenges. After our session, you and your team will actively use AI — not just know about it.",
    starting_price: "Starting at ₱4,999",
    estimated_timeline: "1–3 days",
    status: "active",
    featured: false,
    icon: "🎓",
    best_for: ["Small Businesses", "Professionals", "Schools", "Clinics", "NGOs", "Freelancers"],
    inclusions: [
      "Pre-training needs assessment",
      "Custom training plan for your industry and role",
      "Half-day live training session (3–4 hours)",
      "Hands-on practice with real business scenarios",
      "AI Prompt Library (30+ tested prompts for your use case)",
      "Recording of the session",
      "Follow-up Q&A session (30 min, within 7 days)",
      "AI Tools Guide (PDF reference)",
    ],
    exclusions: [
      "Ongoing coaching or mentorship",
      "Custom software development",
      "AI system setup or deployment",
      "Hardware or device setup",
      "More than 10 participants (enterprise rate applies)",
    ],
    stack: [
      { category: "AI", technology: "ChatGPT" },
      { category: "AI", technology: "Claude" },
      { category: "AI", technology: "Gemini" },
    ],
    requirements: [
      "Number of participants",
      "Industry and job roles of participants",
      "Current AI tool usage (if any)",
      "Main business challenges you want AI to solve",
      "Laptop or device for each participant",
      "Stable internet connection",
    ],
    deliverables: [
      "Live training session (3–4 hours)",
      "AI Prompt Library (30+ prompts, Google Doc)",
      "Training recording",
      "AI Tools Reference Guide (PDF)",
      "Follow-up Q&A session",
      "Certificate of Completion for participants",
    ],
    addons: [
      { addon_name: "Full-Day Training", description: "Extended 7-hour training covering advanced topics", price: "₱7,999" },
      { addon_name: "Monthly Coaching", description: "1 monthly coaching call to continue building AI skills", price: "₱1,999/month" },
      { addon_name: "Department-Specific Training", description: "Separate sessions for different teams (sales, operations, marketing)", price: "₱4,999/session" },
      { addon_name: "Custom Prompt Library", description: "100+ custom prompts built specifically for your business workflows", price: "₱2,999" },
    ],
    faqs: [
      { question: "Do participants need prior AI experience?", answer: "No. Training is designed for complete beginners. We start from the basics and progress to practical business applications within the same session." },
      { question: "Can training be done online?", answer: "Yes. We conduct training via Zoom or Google Meet. In-person is available in Metro Manila and selected areas in the Philippines." },
      { question: "How many people can attend one session?", answer: "Up to 10 people at standard rates. Larger groups (11–50) are available at enterprise rates — contact us for a quote." },
      { question: "What AI tools will we learn?", answer: "We focus on ChatGPT, Claude, and Gemini — the three most powerful and accessible AI tools for business. We also introduce other tools relevant to your specific industry." },
      { question: "Will this actually change how we work?", answer: "Yes — if you apply it. We design training around your real tasks so you leave knowing exactly how to use AI in your daily workflow. Most participants report saving 2–5 hours per week within the first month." },
    ],
    notes: "Training is a trust-builder and door opener. Most clients who attend training convert to other services within 90 days. Position as a team investment, not an expense. School and corporate bulk bookings are highly profitable.",
  },
];
