export type SeedService = {
  id: string;
  service_name: string;
  slug: string;
  category: string;
  short_description: string;
  product_brief: string;
  starting_price: string;
  estimated_timeline: string;
  status: string;
  featured: boolean;
  icon: string;
  best_for: string[];
  inclusions: string[];
  exclusions: string[];
  stack: { category: string; technology: string }[];
  requirements: string[];
  deliverables: string[];
  addons: { addon_name: string; description: string; price: string }[];
  faqs: { question: string; answer: string }[];
  notes: string;
};

export const DEFAULT_SERVICES: SeedService[] = [
  {
    id: "svc-website-design-development",
    service_name: "Website Design & Development",
    slug: "website-design-development",
    category: "Website Design & Development",
    short_description: "Professional, mobile-friendly websites — landing pages, business sites, portfolios, blogs, and e-commerce — built fast and optimized to be found on Google.",
    product_brief: "Every business needs a professional online presence that's actually built to be found. A website from Cyberussell is more than a pretty page — it's a 24/7 sales tool combined with real on-page SEO from day one: keyword research, meta tags, Search Console setup, and a technical foundation that Google can crawl properly. We handle landing pages, business sites, portfolios, blogs, membership sites, and e-commerce, plus redesigns of existing sites that are outdated or underperforming. We combine modern web design with AI-assisted content writing so you get a site that looks great, loads fast, and ranks — without needing any technical knowledge yourself.",
    starting_price: "₱7,999",
    estimated_timeline: "5–7 business days",
    status: "active",
    featured: true,
    icon: "🌐",
    best_for: ["Small Businesses", "Restaurants", "Clinics", "Professionals", "Freelancers", "Real Estate", "Schools", "E-commerce"],
    inclusions: [
      "Discovery & planning session",
      "Up to 5 pages (Home, About, Services, Contact, + 1 custom page)",
      "Mobile-responsive design",
      "AI-assisted copywriting for all pages",
      "On-page SEO (meta tags, headings, sitemap, keyword research)",
      "Google Search Console setup and submission",
      "Contact form setup",
      "Google Maps integration",
      "Social media links",
      "Deployment to custom domain",
      "1 round of revisions after delivery",
    ],
    exclusions: [
      "Domain registration & annual renewal",
      "Hosting fees (after free tier) — see Website Hosting & Maintenance",
      "E-commerce functionality beyond a basic storefront (available as add-on)",
      "Ongoing monthly maintenance — see Website Hosting & Maintenance",
      "Logo design (available as add-on)",
      "Stock photography (client must provide or purchase)",
      "Monthly SEO management and link building (available as add-on)",
    ],
    stack: [
      { category: "Frontend", technology: "Next.js" },
      { category: "Frontend", technology: "React" },
      { category: "Frontend", technology: "Tailwind" },
      { category: "Frontend", technology: "TypeScript" },
      { category: "Hosting", technology: "Vercel" },
      { category: "AI", technology: "Claude" },
      { category: "Analytics", technology: "Google Analytics" },
      { category: "Analytics", technology: "Search Console" },
    ],
    requirements: [
      "Business name and tagline",
      "Logo file (PNG or SVG)",
      "Brand colors (hex codes or references)",
      "Business photos (minimum 5)",
      "List of services with descriptions",
      "Contact information (address, phone, email)",
      "Preferred domain name",
      "Google account (for Google Maps, Analytics, Search Console)",
      "Target location and main competitors (for SEO)",
    ],
    deliverables: [
      "Live website on your domain",
      "Source code (GitHub repository)",
      "Admin access credentials",
      "On-page SEO report and keyword research",
      "Training video (how to update content)",
    ],
    addons: [
      { addon_name: "Logo Design", description: "Professional logo in PNG, SVG, and PDF formats", price: "₱2,499" },
      { addon_name: "Extra Pages", description: "Each additional page beyond the 5-page limit", price: "₱999/page" },
      { addon_name: "E-commerce Setup", description: "Full online store with cart and payments", price: "₱4,999" },
      { addon_name: "Monthly SEO Management", description: "Ongoing SEO monitoring, keyword tracking, and monthly report", price: "₱1,999/month" },
      { addon_name: "Local SEO", description: "Google Business Profile optimization for local search visibility", price: "₱1,499" },
    ],
    faqs: [
      { question: "Do I need to know how to code?", answer: "Not at all. We handle everything technical. You just provide your content and feedback, and we deliver a ready-to-use, SEO-ready website." },
      { question: "How long does it take?", answer: "Typically 5–7 business days after we receive all required materials from you. Delays in providing content will extend the timeline." },
      { question: "Can you redesign my existing website?", answer: "Yes. We redesign existing sites, migrate them to a faster platform, or run an SEO improvement pass without a full rebuild." },
      { question: "Will this actually rank on Google?", answer: "We build in on-page SEO from the start and can add keyword research and a competitor audit. No agency can guarantee first-page rankings, but the technical foundation is done right from day one." },
      { question: "Is hosting included?", answer: "Deployment is included. Vercel's free tier covers most small business websites. If your traffic grows, hosting costs may apply — see Website Hosting & Maintenance for ongoing care." },
    ],
    notes: "Upsell opportunity: offer the Hosting & Maintenance retainer and Monthly SEO Management together right after launch. Most restaurants and clinics need the Google Maps + booking integration — cross-sell Custom Web Applications for booking systems.",
  },
  {
    id: "svc-custom-web-applications",
    service_name: "Custom Web Applications",
    slug: "custom-web-applications",
    category: "Custom Web Applications",
    short_description: "Tailor-made web applications built to solve your exact business problem — inventory systems, booking platforms, CRM tools, and fast no-code MVPs.",
    product_brief: "Off-the-shelf software rarely fits your business perfectly. Custom Web Applications from Cyberussell means you get exactly what you need — an inventory tracking system for your warehouse, a booking platform for your clinic, a customer database for your sales team, or a custom dashboard for your operations. For complex, long-term systems we build full-stack with Next.js and Supabase. For fast MVPs, SaaS validation, or internal tools that need to ship in days instead of months, we build on Bubble.io — the world's most powerful no-code platform — with full ownership transferred to your own account.",
    starting_price: "₱8,999",
    estimated_timeline: "1–6 weeks (scoped per project)",
    status: "active",
    featured: false,
    icon: "💻",
    best_for: ["Small Businesses", "Clinics", "Restaurants", "Startups", "Schools", "Real Estate", "E-commerce"],
    inclusions: [
      "Requirements gathering and system design",
      "Database architecture and setup",
      "Full-stack web application development (or Bubble.io build for faster MVPs)",
      "User authentication and role management",
      "Admin dashboard",
      "Mobile-responsive interface",
      "Testing and bug fixes",
      "Deployment to production",
      "Technical documentation",
      "Training session (1 hour)",
    ],
    exclusions: [
      "Native mobile app (iOS/Android) — see Mobile App Development",
      "Third-party API subscription costs (e.g. Bubble.io plan)",
      "Ongoing hosting fees",
      "Feature additions after project scope is defined",
      "Data migration from existing legacy systems (available as add-on)",
    ],
    stack: [
      { category: "Frontend", technology: "Next.js" },
      { category: "Frontend", technology: "React" },
      { category: "Frontend", technology: "TypeScript" },
      { category: "Frontend", technology: "Tailwind" },
      { category: "Frontend", technology: "Bubble.io" },
      { category: "Backend", technology: "Supabase" },
      { category: "Backend", technology: "PostgreSQL" },
      { category: "Hosting", technology: "Vercel" },
    ],
    requirements: [
      "Detailed description of the software's purpose",
      "List of features and user flows (can be rough)",
      "User roles (who will use it: admin, staff, customers)",
      "Any existing data that needs to be imported",
      "Preferred domain or subdomain",
      "Design preferences or references",
    ],
    deliverables: [
      "Live web application on your domain",
      "Source code (GitHub repository) or full Bubble.io account ownership",
      "Database schema documentation",
      "Admin access and credentials",
      "User manual (PDF)",
      "Training session (1 hour)",
    ],
    addons: [
      { addon_name: "Data Migration", description: "Import and clean data from existing systems (Excel, old software, etc.)", price: "₱4,999+" },
      { addon_name: "Monthly Support", description: "Bug fixes, minor feature updates, and performance monitoring", price: "₱2,999/month" },
      { addon_name: "AI Features", description: "Integrate Claude or OpenAI into the application for intelligent features", price: "₱2,999" },
      { addon_name: "Stripe / PayMongo Payments", description: "Full payment processing integration", price: "₱2,499" },
    ],
    faqs: [
      { question: "How is this different from buying off-the-shelf software?", answer: "Generic software has features you don't need and lacks features specific to your business. Custom software is built exactly for your workflow, reducing friction and training time." },
      { question: "Should I go custom-built or Bubble.io?", answer: "Bubble.io is faster and cheaper for MVPs and validating an idea. Full custom development is the better investment for long-term, highly custom, or high-scale systems." },
      { question: "Can I add features later?", answer: "Yes. We build with scalability in mind. Additional features can be scoped and priced after the initial project." },
      { question: "Is my data secure?", answer: "Yes. Custom builds use Supabase (PostgreSQL) with row-level security and proper authentication. Bubble builds run on Bubble's production-grade infrastructure." },
    ],
    notes: "Highest-value service. Requires the most detailed discovery call. Always get requirements in writing before starting. Use Bubble.io for MVP-type projects where the client wants to validate an idea quickly; use custom development for long-term or high-scale systems.",
  },
  {
    id: "svc-ai-automation-solutions",
    service_name: "AI Automation Solutions",
    slug: "ai-automation-solutions",
    category: "AI Automation Solutions",
    short_description: "Automate repetitive business tasks with AI-powered workflows, custom chatbots and assistants, and a month of AI-assisted content — save hours every week.",
    product_brief: "Repetitive tasks are the biggest time drain in any business. AI Automation Solutions from Cyberussell identifies the workflows eating your time — manual data entry, follow-up messages, report generation, customer questions — and replaces them with automated systems and purpose-built AI assistants trained on your business context. We also handle the content side: a month of AI-assisted social posts, blog outlines, and newsletters so you're never starting from a blank page. We use a combination of n8n, Google Apps Script, and Claude/OpenAI to build systems tailored to your exact operations — no technical knowledge required.",
    starting_price: "₱1,999",
    estimated_timeline: "3–10 business days",
    status: "active",
    featured: true,
    icon: "⚙️",
    best_for: ["Small Businesses", "Freelancers", "Clinics", "Restaurants", "E-commerce", "Startups", "Real Estate", "Content Creators"],
    inclusions: [
      "Business process audit (identify automation opportunities)",
      "Up to 3 automation workflows",
      "Integration with existing tools (Gmail, Google Sheets, WhatsApp, Facebook, etc.)",
      "AI chatbot or assistant with a knowledge base built from your business info",
      "Custom prompt engineering and system instructions",
      "A month of AI-assisted content (20 social posts, 4 blog outlines, 2 newsletters)",
      "Testing and quality assurance",
      "Documentation of all workflows",
      "1-hour walkthrough and training session",
      "30-day post-launch support",
    ],
    exclusions: [
      "More than 3 workflows or one platform integration (available as add-on)",
      "Custom app or software development — see Custom Web Applications",
      "Paid API costs (third-party tools, OpenAI/Anthropic usage)",
      "Ongoing workflow or content management",
      "Content scheduling and posting",
    ],
    stack: [
      { category: "Automation", technology: "n8n" },
      { category: "Automation", technology: "Google Apps Script" },
      { category: "Automation", technology: "Make" },
      { category: "AI", technology: "Claude" },
      { category: "AI", technology: "OpenAI API" },
      { category: "AI", technology: "Anthropic API" },
      { category: "Backend", technology: "Supabase" },
      { category: "Analytics", technology: "Google Analytics" },
    ],
    requirements: [
      "Description of current manual processes (written or voice note)",
      "Access to tools you want connected (Google, Facebook, etc.)",
      "Your business information (services, pricing, policies, FAQs)",
      "Preferred tone and personality for the AI",
      "Topics or themes for content",
      "Google account for Google Sheets/Apps Script",
    ],
    deliverables: [
      "Up to 3 live automation workflows",
      "Live AI chatbot or assistant on your chosen platform",
      "Knowledge base and system prompt documentation",
      "20 social captions, 4 blog articles, 2 newsletter drafts, content calendar",
      "Workflow documentation and n8n exports",
      "30-day support access",
    ],
    addons: [
      { addon_name: "Additional Workflows", description: "Each workflow beyond the 3 included", price: "₱1,500/workflow" },
      { addon_name: "Monthly Monitoring", description: "Monthly check-in, error fixes, and workflow optimization", price: "₱1,999/month" },
      { addon_name: "Additional Platform", description: "Deploy the same AI to a second platform (e.g. website + WhatsApp)", price: "₱1,999" },
      { addon_name: "Monthly Content Package", description: "Recurring monthly content: posts, blogs, and newsletters", price: "₱1,999/month" },
      { addon_name: "Content Scheduling", description: "Schedule and publish all content for you for the month", price: "₱999/month" },
    ],
    faqs: [
      { question: "What kinds of tasks can be automated?", answer: "Common examples include: sending follow-up messages to leads, generating weekly reports from Google Sheets, auto-posting to social media, processing inquiry forms, and scheduling reminders." },
      { question: "What's the difference between a chatbot and an AI system?", answer: "A chatbot follows fixed scripts. An AI system understands natural language, handles unexpected questions, and gives answers based on your specific business knowledge." },
      { question: "Will the AI-written content sound robotic?", answer: "No. We use AI to draft and structure, then refine the content to match your brand voice. The final output reads naturally and professionally." },
      { question: "Are there ongoing costs?", answer: "AI API usage (OpenAI or Anthropic) is billed directly to you. Most small businesses spend ₱500–₱2,000/month on API costs depending on volume." },
    ],
    notes: "This is the highest-growth service. Position as ROI-positive: replaces a human customer service rep or content writer. Great upsell: monthly monitoring and monthly content package.",
  },
  {
    id: "svc-mobile-app-development",
    service_name: "Mobile App Development",
    slug: "mobile-app-development",
    category: "Mobile App Development",
    short_description: "Installable, mobile-first apps for your business — progressive web apps and cross-platform builds with React Native/Expo, without native app-store overhead.",
    product_brief: "You don't need two separate native apps to get a real mobile presence. Mobile App Development from Cyberussell covers Progressive Web Apps (installable, offline-capable, app-store-free) and cross-platform apps built with React Native/Expo that run on both iOS and Android from a single codebase. This is ideal for ordering apps, booking apps, and internal staff tools that need to feel native without native-app timelines or cost. We handle design, build, testing, and — for cross-platform builds — App Store/Play Store submission support.",
    starting_price: "₱14,999",
    estimated_timeline: "2–8 business days for PWA; 3–6 weeks for cross-platform",
    status: "active",
    featured: false,
    icon: "📱",
    best_for: ["Startups", "Restaurants", "Clinics", "E-commerce", "Small Businesses"],
    inclusions: [
      "Mobile UI/UX design and wireframes",
      "PWA build (installable, offline-capable, push notifications) or React Native/Expo cross-platform build",
      "App icon, splash screen, and branding assets",
      "Integration with your existing backend or a new one built alongside it",
      "Testing across real devices and screen sizes",
      "App Store / Play Store submission support (cross-platform builds)",
      "2 weeks of post-launch support",
    ],
    exclusions: [
      "Apple Developer / Google Play developer account fees (paid by client)",
      "Complex real-time features (e.g. multiplayer, video calling)",
      "Ongoing app maintenance — see Website Hosting & Maintenance",
      "Backend development beyond what's scoped for the app",
    ],
    stack: [
      { category: "Frontend", technology: "React Native" },
      { category: "Frontend", technology: "Next.js" },
      { category: "Backend", technology: "Supabase" },
      { category: "Hosting", technology: "Vercel" },
    ],
    requirements: [
      "Description of what the app should do",
      "User flows and key features",
      "Design references or mood board",
      "Apple Developer / Google Play account (for cross-platform submission)",
      "Access to your existing backend or system, if applicable",
    ],
    deliverables: [
      "Live installable PWA, or cross-platform build submitted to app stores",
      "Source code",
      "App icon, splash screen, and branding assets",
      "Admin/analytics dashboard access",
      "Walkthrough video and feature documentation",
    ],
    addons: [
      { addon_name: "Push Notifications", description: "Custom push notification system for re-engagement", price: "₱1,999" },
      { addon_name: "Offline Data Sync", description: "Full offline data sync for cross-platform apps", price: "₱3,499" },
      { addon_name: "Monthly Maintenance", description: "Bug fixes, OS compatibility updates, and minor feature tweaks", price: "₱1,999/month" },
      { addon_name: "Stripe / PayMongo Payments", description: "Full payment processing integration", price: "₱2,499" },
    ],
    faqs: [
      { question: "Should I build a PWA or a cross-platform app?", answer: "A PWA is faster to ship with no app-store approval wait and instant updates. A React Native/Expo build is better if you need deep device features or an actual app-store presence." },
      { question: "Do you handle App Store and Play Store submission?", answer: "Yes, for cross-platform builds. Developer account fees (Apple/Google) are paid directly by you." },
      { question: "Will it work offline?", answer: "PWAs support offline caching for core screens. Full offline data sync for cross-platform apps is available as an add-on." },
      { question: "Can this connect to my existing website or system?", answer: "Yes — the app can connect to your existing backend, or we can build a lightweight backend alongside it." },
    ],
    notes: "New service line — no track record yet, so lead with PWA (fastest, cheapest, lowest risk) for first clients before pitching full cross-platform builds. Good upsell for existing Custom Web Applications or Website clients who want a mobile companion.",
  },
  {
    id: "svc-website-hosting-maintenance",
    service_name: "Website Hosting & Maintenance",
    slug: "website-hosting-maintenance",
    category: "Website Hosting & Maintenance",
    short_description: "Monthly website care — hosting setup, updates, backups, performance monitoring, and security checks — so your site stays fast and secure year-round.",
    product_brief: "A website is not a one-time project — it's a living asset that needs regular care. Website Hosting & Maintenance from Cyberussell gives you peace of mind with domain/hosting setup, monthly updates, automated backups, uptime monitoring, and security checks. We handle the technical side so you can focus on running your business. Whether we built your site or not, we're your dedicated website team — most business owners don't realize how fragile an unmaintained website becomes over time. We prevent problems before they become emergencies.",
    starting_price: "₱999/month",
    estimated_timeline: "Ongoing monthly service",
    status: "active",
    featured: false,
    icon: "🛠️",
    best_for: ["Small Businesses", "Restaurants", "Clinics", "Professionals", "Schools", "Real Estate"],
    inclusions: [
      "Domain and hosting setup guidance",
      "Monthly content updates (up to 3 changes)",
      "Plugin and dependency updates",
      "Automated daily backups",
      "Uptime monitoring (24/7)",
      "Monthly performance report",
      "Security scan and SSL check",
      "Broken link check",
      "Priority support response (within 24 hours)",
    ],
    exclusions: [
      "Major redesign or new pages — see Website Design & Development",
      "New feature development — see Custom Web Applications",
      "SEO management (available as add-on)",
      "Content creation (blog articles, social media) — see AI Automation Solutions",
      "E-commerce order management",
    ],
    stack: [
      { category: "Frontend", technology: "Next.js" },
      { category: "Hosting", technology: "Vercel" },
      { category: "Analytics", technology: "Google Analytics" },
      { category: "Analytics", technology: "Search Console" },
    ],
    requirements: [
      "Website URL and admin access",
      "Hosting platform access",
      "Domain registrar access (for SSL monitoring)",
      "Google account (for Analytics/Search Console)",
    ],
    deliverables: [
      "Monthly maintenance report",
      "Backup confirmation",
      "Performance metrics summary",
      "List of changes made each month",
    ],
    addons: [
      { addon_name: "Emergency Support", description: "Same-day response for critical issues (site down, hacked, etc.)", price: "₱1,499/incident" },
      { addon_name: "Content Updates (Extra)", description: "Additional content changes beyond the 3 included", price: "₱299/change" },
      { addon_name: "SEO Monthly Add-on", description: "Add monthly SEO monitoring and reporting", price: "₱1,499/month" },
      { addon_name: "New Page", description: "Add a new page to the existing website", price: "₱999/page" },
    ],
    faqs: [
      { question: "What counts as a 'content update'?", answer: "Changing text, swapping an image, updating a price, adding a phone number, changing business hours — any edit that doesn't require building a new section or page." },
      { question: "What happens if my site goes down?", answer: "Our uptime monitoring alerts us immediately. We investigate and fix the issue within our agreed response time (24 hours standard, same-day with the Emergency Support add-on)." },
      { question: "Can I cancel anytime?", answer: "Yes. This is a month-to-month service. Cancel anytime with 30 days notice." },
      { question: "Do you maintain websites you didn't build?", answer: "Yes, if the site is built with technologies we support (Next.js, WordPress, Webflow, Wix). We'll do an initial audit first to assess the site's condition." },
    ],
    notes: "Highest recurring revenue product. Every website client should be offered this immediately after launch. Bundle: Website + 3 months maintenance at a discount to get them on the retainer.",
  },
  {
    id: "svc-ai-technology-consulting",
    service_name: "AI & Technology Consulting",
    slug: "ai-technology-consulting",
    category: "AI & Technology Consulting",
    short_description: "Hands-on AI training, market research, and business documentation — practical groundwork and strategy before (or alongside) any build.",
    product_brief: "Not every engagement starts with a build. AI & Technology Consulting from Cyberussell covers the strategy and groundwork: hands-on AI training for your team, AI-powered market and competitor research delivered as a clean actionable report, and professional business documentation (SOPs, handbooks, agreements, business plans) that formalizes how your business runs. We don't teach theory or produce generic reports — everything is tailored to your industry, your role, and your specific business challenges, using AI tools to research and draft in hours instead of weeks, then refined by a human.",
    starting_price: "₱1,999",
    estimated_timeline: "1–5 business days",
    status: "active",
    featured: false,
    icon: "🎓",
    best_for: ["Small Businesses", "Professionals", "Schools", "Clinics", "NGOs", "Freelancers", "Startups"],
    inclusions: [
      "Needs assessment call or written brief",
      "Custom plan for your industry, role, or research goal",
      "Half-day live AI training session (3–4 hours) with hands-on practice",
      "AI Prompt Library (30+ tested prompts) and AI Tools reference guide",
      "Market overview, top-5 competitor analysis, SWOT, and recommendations",
      "Up to 3 professional business documents, AI-assisted with human refinement",
      "Recording of training sessions and a follow-up Q&A",
      "Delivered in Word (.docx) and PDF formats",
    ],
    exclusions: [
      "Ongoing coaching or mentorship (available as add-on)",
      "Custom software development — see Custom Web Applications",
      "Primary research (surveys, interviews, focus groups)",
      "Legal review or notarization of documents (consult a licensed attorney)",
      "More than 10 training participants (enterprise rate applies)",
    ],
    stack: [
      { category: "AI", technology: "Claude" },
      { category: "AI", technology: "ChatGPT" },
      { category: "AI", technology: "Gemini" },
    ],
    requirements: [
      "Number of participants and their roles (for training)",
      "Research topic, target market, and known competitors (for research)",
      "Business name, type, and description of services (for documentation)",
      "Main business challenges you want addressed",
      "Laptop/device and stable internet connection (for training)",
    ],
    deliverables: [
      "Live training session (3–4 hours), recording, and prompt library",
      "Market research report (PDF, 10–20 pages) and competitor spreadsheet",
      "Up to 3 business documents in Word and PDF",
      "AI Tools reference guide",
      "Certificate of completion for training participants",
    ],
    addons: [
      { addon_name: "Full-Day Training", description: "Extended 7-hour training covering advanced topics", price: "₱7,999" },
      { addon_name: "Monthly Coaching", description: "1 monthly coaching call to continue building AI skills", price: "₱1,999/month" },
      { addon_name: "Investor Pitch Deck", description: "Professional 10-slide pitch deck based on research findings", price: "₱3,999" },
      { addon_name: "Additional Document", description: "Each business document beyond the 3 included", price: "₱999/document" },
    ],
    faqs: [
      { question: "Do participants need prior AI experience?", answer: "No. Training is designed for complete beginners and progresses to practical business applications within the same session." },
      { question: "How accurate is AI-powered market research?", answer: "Highly effective for publicly available information — market trends, competitor positioning, consumer behavior. Key data points are verified and clearly noted as estimated vs. confirmed." },
      { question: "Are the business documents legally binding?", answer: "They follow standard professional formats. For legally sensitive agreements, we recommend having a licensed attorney review before use." },
      { question: "Can training be done online?", answer: "Yes, via Zoom or Google Meet. In-person is available in Metro Manila and selected areas in the Philippines." },
    ],
    notes: "Training and research are trust-builders and door-openers. Most clients who take training or research convert to a build (website, app, or automation) within 90 days. Position as a low-risk first engagement.",
  },
];
