/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://www.cyberussell.com',
  generateRobotsTxt: true,
  changefreq: 'weekly',
  priority: 0.7,
  additionalPaths: async (config) => [
    { loc: '/', priority: 1.0, changefreq: 'weekly' },
    { loc: '/skill-finder', priority: 0.9, changefreq: 'weekly' },
    { loc: '/start-here', priority: 0.9, changefreq: 'monthly' },
    { loc: '/tools', priority: 0.9, changefreq: 'weekly' },
    { loc: '/tools/scam-scanner', priority: 0.8, changefreq: 'monthly' },
    { loc: '/tools/prompt-forge', priority: 0.8, changefreq: 'monthly' },
    { loc: '/tools/bio-generator', priority: 0.8, changefreq: 'monthly' },
    { loc: '/earn', priority: 0.8, changefreq: 'monthly' },
    { loc: '/learn', priority: 0.8, changefreq: 'monthly' },
    { loc: '/blog', priority: 0.8, changefreq: 'weekly' },
    { loc: '/platforms', priority: 0.8, changefreq: 'monthly' },
    { loc: '/resources', priority: 0.7, changefreq: 'monthly' },
    { loc: '/guides/8-ways', priority: 0.7, changefreq: 'monthly' },
    { loc: '/guides/worksheet', priority: 0.7, changefreq: 'monthly' },
    { loc: '/guides/scam-checker', priority: 0.7, changefreq: 'monthly' },
    { loc: '/guides/claude-ai', priority: 0.7, changefreq: 'monthly' },
    { loc: '/faq', priority: 0.6, changefreq: 'monthly' },
    { loc: '/about', priority: 0.6, changefreq: 'monthly' },
    { loc: '/contact', priority: 0.6, changefreq: 'monthly' },
    { loc: '/share', priority: 0.5, changefreq: 'monthly' },
    { loc: '/disclaimer', priority: 0.3, changefreq: 'yearly' },
    { loc: '/terms', priority: 0.3, changefreq: 'yearly' },
    { loc: '/privacy', priority: 0.3, changefreq: 'yearly' },
  ],
};
