import Link from 'next/link'
import { requireAdmin } from '@/lib/territory-management-system/modules/auth/queries'
import { listBatches } from '@/lib/territory-management-system/modules/assignment/queries'
import PageHeader from '@/components/territory-management-system/dashboard/PageHeader'
import DataTable from '@/components/territory-management-system/dashboard/DataTable'

// Read-only for Admin — generating/regenerating/deleting assignments is the Territory Group
// Leader's responsibility (see the Group Leader dashboard), not the Admin's. This page exists
// so Admins retain full oversight of what's been generated without being able to change it.
export default async function AssignmentsPage() {
  const { supabase, congregation } = await requireAdmin()
  const batches = await listBatches(supabase, congregation.id)

  return (
    <div>
      <PageHeader
        title="Assignments"
        subtitle="Territory assignment batches generated by your Territory Group Leader."
      />
      <DataTable
        columns={[
          {
            header: 'Date',
            cell: (b) => (
              <Link href={`/territory-management-system/dashboard/assignments/${b.id}`} className="font-medium hover:text-[#2563EB]">
                {b.assignment_date}
              </Link>
            ),
            sortValue: (b) => b.assignment_date,
          },
          { header: 'Ministry Partners Requested', cell: (b) => b.requested_partnership_count, sortValue: (b) => b.requested_partnership_count },
          {
            header: 'Created',
            cell: (b) => new Date(b.created_at).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' }),
          },
        ]}
        rows={batches}
        emptyMessage="No assignments generated yet."
      />
    </div>
  )
}
