import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service | Cyberussell",
  description: "Terms of Service for Cyberussell — rules and conditions for using this website.",
  alternates: { canonical: "https://www.cyberussell.com/terms" },
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="min-h-screen bg-[#0F0F1A] px-6 md:px-10 py-16 max-w-3xl mx-auto">
        <h1 className="font-sans text-[32px] font-bold text-white mb-3">Terms of Service</h1>
        <p className="font-[family-name:var(--font-inter)] text-[13px] text-white/35 mb-10">Last updated: June 2026</p>

        <div className="font-[family-name:var(--font-inter)] text-[15px] text-white/65 leading-[1.9] flex flex-col gap-8">
          <section>
            <h2 className="font-sans text-[18px] font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing and using Cyberussell ("this website"), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use this website.</p>
          </section>

          <section>
            <h2 className="font-sans text-[18px] font-bold text-white mb-3">2. Use of Content</h2>
            <p>All content on this website — including guides, articles, tools, and downloadable resources — is provided for informational and educational purposes only. You may read, share, and reference the content with proper attribution. You may not copy, republish, or sell our content without written permission.</p>
          </section>

          <section>
            <h2 className="font-sans text-[18px] font-bold text-white mb-3">3. AI Tools</h2>
            <p>The AI tools on this website are provided "as is" for free. Results generated by these tools are not guaranteed to be accurate, complete, or suitable for any specific purpose. Always use your own judgment when acting on AI-generated content.</p>
          </section>

          <section>
            <h2 className="font-sans text-[18px] font-bold text-white mb-3">4. No Professional Advice</h2>
            <p>Nothing on this website constitutes legal, financial, career, or professional advice. All information is general in nature and should not replace professional consultation for your specific situation.</p>
          </section>

          <section>
            <h2 className="font-sans text-[18px] font-bold text-white mb-3">5. Third-Party Links</h2>
            <p>This website contains links to third-party websites, including affiliate links. We are not responsible for the content, privacy practices, or actions of any third-party websites. Some links may earn us a commission at no extra cost to you.</p>
          </section>

          <section>
            <h2 className="font-sans text-[18px] font-bold text-white mb-3">6. Digital Products</h2>
            <p>All digital product sales are final unless otherwise stated. By purchasing a product, you agree to our refund policy as stated on the product page at the time of purchase.</p>
          </section>

          <section>
            <h2 className="font-sans text-[18px] font-bold text-white mb-3">7. Intellectual Property</h2>
            <p>All original content, branding, tools, and designs on this website are the intellectual property of Cyberussell. Unauthorized use is prohibited.</p>
          </section>

          <section>
            <h2 className="font-sans text-[18px] font-bold text-white mb-3">8. Changes to Terms</h2>
            <p>We reserve the right to update these terms at any time. Continued use of this website after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="font-sans text-[18px] font-bold text-white mb-3">9. Contact</h2>
            <p>Questions about these terms? <a href="/contact" className="text-[#FFD23F] hover:text-white transition-colors">Contact us here</a>.</p>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}
